version: 2
updates:
  # Enable version updates for docker
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "monthly"
    target-branch: universal
    # labels:
    #   - "docker dependencies"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "monthly"
    target-branch: python
    # labels:
    #   - "docker dependencies"

  - package-ecosystem: "github-actions"
    # Workflow files stored in the
    # default location of `.github/workflows`
    directory: "/"
    schedule:
      interval: "monthly"
    # labels:
    #   - "workflow dependencies"
