name: API Request Workflow

on:
  schedule:
    - cron: '* * * * *'  # 每分钟运行一次（注意：实际最小间隔可能为5分钟）
  workflow_dispatch: 

jobs:
  call_api:
    runs-on: ubuntu-latest
    steps:
      - name: api request
        id: api_call
        run: |
          response=$(curl -s -G 'https://api.live.bilibili.com/room/v1/Room/get_info' \
            --data-urlencode 'room_id=1')
          
          # 使用 jq 解析 JSON 数据并提取 message 键的值
          live_status=$(echo "$response" | jq -r '.live_status')
          
          # 将 live_status 值保存为环境变量供后续步骤使用
          echo "LIVE_STATUS=$live_status" >> $GITHUB_ENV
          
          # 如果需要将该变量作为步骤输出，可以使用如下方式：
          echo "::set-output name=live_status::$live_status"
          
      - name: 使用 live_status 变量
        run: |
          echo "当前 live_status 变量的值为: $LIVE_STATUS"
