name: Bilibili Live Status Check

on:
  #schedule:
    #- cron: '* * * * *'  
  workflow_dispatch: 

jobs:
  fetch_live_status:
    runs-on: ubuntu-latest
    steps:
      - name: api-get
        id: live_status_api
        run: |
          response=$(curl -s -G 'https://api.live.bilibili.com/room/v1/Room/get_info' \
            --data-urlencode 'room_id=13')  #'room_id=804192')
          echo "response: $response"
          live_status=$(echo "$response" | jq -r '.data.live_status')
          echo "live_status get: $live_status"
          echo "LIVE_STATUS=$live_status" >> $GITHUB_ENV
          echo "::set-output name=live_status::$live_status"
          echo "当前 live_status 变量的值为: $LIVE_STATUS"
          
      - name: trigger for next workflow
        if: ${{ env.LIVE_STATUS == '1' }} 
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/dispatches \
            -d '{"event_type": "live_status_active", "client_payload": {"live_status": "'"${LIVE_STATUS}"'"}}'
