name: remote ssh command
on: 
  schedule: 
    # Daily at 8:20 UTC
    - cron: '20 8 * * *'
jobs: 
  start_cs: 
    runs-on: ubuntu-latest
    steps: 
      # fill this
      - run : gh codespace ssh --codespace "Shikan" 
  run_command: 
    runs-on: ubuntu-latest
    steps:
      # run commands using "gh cs ssh"
      
    
