name: start and run command
on:
  repository_dispatch:
    types: [live_status_active]
  workflow_dispatch:

jobs: 
  start_cs: 
    runs-on: ubuntu-latest
    steps: 
      - name: Codespace Scheduler
        uses: ud803/github-codespace-scheduler@v1.0.6
        env:
          GITHUB_AUTH: ${{ secrets.GH_TOKEN }}
        with:
          CODESPACE_NAME: "cuddly-umbrella-9vgg4vwv77qcxv6j"
          #WAIT_SECONDS: 30
  run_command: 
    runs-on: ubuntu-latest
    steps:
      - run : gh codespace ssh --codespace "cuddly-umbrella-9vgg4vwv77qcxv6j" whoami 
      # ./home/codespace/Desktop/start_all.sh
        env : 
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
