name: Keep cs alive
on: push 
  #schedule: 
    # every 2h during working time
    #- cron: '20 8 * * *'
jobs:
  keep_alive: 
    runs-on: ubuntu-latest
    steps:
        - run : gh codespace ssh --codespace "cuddly-umbrella-9vgg4vwv77qcxv6j" whoami 
          env : 
            GH_TOKEN: ${{ secrets.GH_TOKEN }}
