name: Report remaining open issues
on: 
  schedule: 
    # every 2h during working time
    - cron: '20 8 * * *'
jobs:
  keep_alive: 
    runs-on: ubuntu-latest
    steps:
        - run : gh codespace ssh --codespace "Shikan" whoami 
          env : 
            GH_TOKEN: ${{ secrets.secrets_TOKEN }}
