name: start_cs
on: 
  workflow_dispatch:
jobs: 
  start_cs: 
    runs-on: ubuntu-latest
    steps: 
        - run: |
            curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/user/codespaces/Shikan/start
